version: "3.7"
services:
  frontend:
    image: ghcr.io/jeondawun/kdt1-study-3-team3-front-server:latest
    container-name: docker-frontend-deploy-server
    networks:
      - app

networks:
  app:
    driver: bridge